@echo off
for %%f in (
    "C:\Windows\WinSxS\FileMaps\wow64_windows-defender*.manifest"
    "C:\Windows\WinSxS\FileMaps\x86_windows-defender*.manifest"
    "C:\Windows\WinSxS\FileMaps\amd64_windows-defender*.manifest"
    "C:\Windows\System32\SecurityAndMaintenance_Error.png"
    "C:\Windows\System32\SecurityAndMaintenance.png"
    "C:\Windows\System32\SecurityHealthSystray.exe"
    "C:\Windows\System32\SecurityHealthService.exe"
    "C:\Windows\System32\SecurityHealthHost.exe"
    "C:\Windows\System32\drivers\WdDevFlt.sys"
    "C:\Windows\System32\drivers\WdBoot.sys"
    "C:\Windows\System32\drivers\WdFilter.sys"
    "C:\Windows\System32\wscsvc.dll"
    "C:\Windows\System32\drivers\WdNisDrv.sys"
    "C:\Windows\System32\wscproxystub.dll"
    "C:\Windows\System32\wscisvif.dll"
    "C:\Windows\System32\SecurityHealthProxyStub.dll"
    "C:\Windows\System32\smartscreen.dll"
    "C:\Windows\SysWOW64\smartscreen.dll"
    "C:\Windows\System32\smartscreen.exe"
    "C:\Windows\SysWOW64\smartscreen.exe"
    "C:\Windows\SysWOW64\smartscreenps.dll"
    "C:\Windows\System32\smartscreenps.dll"
    "C:\Windows\System32\SecurityHealthCore.dll"
    "C:\Windows\System32\SecurityHealthSsoUdk.dll"
    "C:\Windows\System32\SecurityHealthUdk.dll"
    "C:\Windows\System32\SecurityHealthAgent.dll"
    "C:\Windows\System32\wscapi.dll"
    "C:\Windows\System32\wscadminui.exe"
    "C:\Windows\system32\drivers\msseccore.sys"
    "C:\Windows\system32\drivers\MsSecFltWfp.sys"
    "C:\Windows\system32\drivers\MsSecFlt.sys"
) do (
    if exist "%%~f" (
        del /f /q "%%~f"
    )
)

for %%f in (
    "C:\ProgramData\Microsoft\Windows Defender"
    "C:\Program Files\Windows Defender"
    "C:\Program Files (x86)\Windows Defender"
    "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection"
    "C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy"
    "C:\Windows\SystemApps\Microsoft.Windows.AppRep.ChxApp_cw5n1h2txyewy"
    "C:\Windows\System32\SecurityHealth"
    "C:\Windows\System32\WebThreatDefSvc"
    "C:\Windows\System32\Tasks\Microsoft\Windows\Windows Defender"
    "C:\Windows\System32\Tasks_Migrated\Microsoft\Windows\Windows Defender"
    "C:\Windows\WinSxS\x86_windows-defender*"
    "C:\Windows\WinSxS\wow64_windows-defender*"
    "C:\Windows\WinSxS\amd64_windows-defender*"
    "C:\Program Files (x86)\Windows Defender Advanced Threat Protection"
    "C:\Program Files\Windows Defender Advanced Threat Protection"
    "C:\ProgramData\Microsoft\Windows Security Health"
    "C:\WINDOWS\System32\drivers\wd"
    "C:\Windows\Containers\WindowsDefenderApplicationGuard.wim"
    "C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\DefenderPerformance"
    "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DefenderPerformance"
    "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Defender"
    "C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\Defender"
    "C:\Windows\Containers\serviced\WindowsDefenderApplicationGuard.wim"
) do (
    if exist "%%~f" (
        rd /s /q "%%~f"
    )
)